#!/usr/bin/env bash

set -u

TESTS_PASSED=0
TESTS_FAILED=0

pass() {
  printf 'PASS: %s\n' "$1"
  TESTS_PASSED=$((TESTS_PASSED + 1))
}

fail() {
  printf 'FAIL: %s\n' "$1"
  TESTS_FAILED=$((TESTS_FAILED + 1))
}

assert_success() {
  local description="$1"
  shift

  if "$@" >/dev/null 2>&1; then
    pass "$description"
  else
    fail "$description"
  fi
}

assert_failure() {
  local description="$1"
  shift

  if "$@" >/dev/null 2>&1; then
    fail "$description"
  else
    pass "$description"
  fi
}

assert_equals() {
  local description="$1"
  local expected="$2"
  local actual="$3"

  if [[ "$expected" == "$actual" ]]; then
    pass "$description"
  else
    fail "$description"
    printf '  expected:\n%s\n' "$expected"
    printf '  actual:\n%s\n' "$actual"
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVKIT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${DEVKIT_ROOT}/03_GENERATORS/execution.sh"
source "${DEVKIT_ROOT}/03_GENERATORS/builtins.sh"

TEST_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/phoenix-provider-generator.XXXXXX")"

cleanup() {
  rm -rf "$TEST_ROOT"
}

trap cleanup EXIT

assert_success \
  "register provider built-in" \
  phoenix::generator_register_builtins

PROVIDER_DEST="${TEST_ROOT}/providers/ricardo"

plan_result="$(
  phoenix::generator_plan \
    "provider" \
    "$PROVIDER_DEST" \
    "PROVIDER_NAME=Ricardo" \
    "COUNTRY=CH"
)"

expected_plan="$(cat <<PLAN
STATUS=PLAN
GENERATOR=provider
DESTINATION=${PROVIDER_DEST}
OVERWRITE=0
DRY_RUN=0
ARTIFACT=${PROVIDER_DEST}/index.sh
ARTIFACT=${PROVIDER_DEST}/manifest.phoenix
PLAN
)"

assert_equals \
  "real provider produces canonical plan" \
  "$expected_plan" \
  "$plan_result"

run_result="$(
  phoenix::generator_run \
    "provider" \
    "$PROVIDER_DEST" \
    "PROVIDER_NAME=Ricardo" \
    "COUNTRY=CH"
)"

expected_run="$(cat <<RESULT
STATUS=SUCCESS
GENERATOR=provider
DESTINATION=${PROVIDER_DEST}
ARTIFACT=${PROVIDER_DEST}/index.sh
ARTIFACT=${PROVIDER_DEST}/manifest.phoenix
RESULT
)"

assert_equals \
  "real provider execution returns canonical result" \
  "$expected_run" \
  "$run_result"

if [[ -f "${PROVIDER_DEST}/index.sh" ]]; then
  pass "provider generator creates index.sh"
else
  fail "provider generator creates index.sh"
fi

if [[ -f "${PROVIDER_DEST}/manifest.phoenix" ]]; then
  pass "provider generator creates manifest.phoenix"
else
  fail "provider generator creates manifest.phoenix"
fi

expected_index="$(cat <<'CONTENT'
#!/usr/bin/env bash

# ==============================================================================
# PHOENIX PROVIDER — Ricardo
# ==============================================================================
#
# Country: CH
#
# Generated by Phoenix DevKit.
#
# ==============================================================================
CONTENT
)"

actual_index="$(
  cat "${PROVIDER_DEST}/index.sh" 2>/dev/null || true
)"

assert_equals \
  "generated index.sh contains rendered provider data" \
  "$expected_index" \
  "$actual_index"

expected_manifest="$(cat <<'CONTENT'
PROVIDER_NAME=Ricardo
COUNTRY=CH
CONTENT
)"

actual_manifest="$(
  cat "${PROVIDER_DEST}/manifest.phoenix" 2>/dev/null || true
)"

assert_equals \
  "generated manifest contains rendered provider data" \
  "$expected_manifest" \
  "$actual_manifest"

DRY_DEST="${TEST_ROOT}/providers/dry-provider"

dry_result="$(
  phoenix::generator_run \
    "provider" \
    "$DRY_DEST" \
    "PROVIDER_NAME=DryProvider" \
    "COUNTRY=CH" \
    "PHOENIX_DRY_RUN=1"
)"

expected_dry="$(cat <<RESULT
STATUS=DRY_RUN
GENERATOR=provider
DESTINATION=${DRY_DEST}
ARTIFACT=${DRY_DEST}/index.sh
ARTIFACT=${DRY_DEST}/manifest.phoenix
RESULT
)"

assert_equals \
  "real provider dry-run returns canonical result" \
  "$expected_dry" \
  "$dry_result"

if [[ ! -e "$DRY_DEST" ]]; then
  pass "real provider dry-run performs zero mutation"
else
  fail "real provider dry-run performs zero mutation"
fi

MISSING_DEST="${TEST_ROOT}/providers/missing-variable"

assert_failure \
  "real provider rejects missing required variable" \
  phoenix::generator_run \
    "provider" \
    "$MISSING_DEST" \
    "PROVIDER_NAME=Incomplete"

if [[ ! -e "$MISSING_DEST" ]]; then
  pass "failed real provider request performs zero mutation"
else
  fail "failed real provider request performs zero mutation"
fi

printf '\n'
printf 'Provider Generator End-to-End Tests\n'
printf '===================================\n'
printf 'Passed: %d\n' "$TESTS_PASSED"
printf 'Failed: %d\n' "$TESTS_FAILED"

if [[ "$TESTS_FAILED" -ne 0 ]]; then
  exit 1
fi

exit 0
